#include "boompi/network/wss_client.h"

#include "boompi/protocol/envelope.h"

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cstring>
#include <limits>
#include <mutex>
#include <sstream>
#include <string>
#include <utility>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#include <ws2tcpip.h>
#else
#include <arpa/inet.h>
#include <cerrno>
#include <fcntl.h>
#include <netinet/in.h>
#include <poll.h>
#include <pthread.h>
#include <signal.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>

namespace boompi::network {
namespace {

constexpr char kWebSocketPath[] = "/ws";
constexpr char kWebSocketGuid[] = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
constexpr std::size_t kMaximumHandshakeBytes = 8192U;
constexpr std::size_t kMaximumWireMessageBytes =
    protocol::kAudioPacketHeaderSize + protocol::kMaximumAudioPayloadBytes;
constexpr std::size_t kSha256Bytes = 32U;
constexpr std::uint8_t kOpcodeContinuation = 0x0U;
constexpr std::uint8_t kOpcodeText = 0x1U;
constexpr std::uint8_t kOpcodeBinary = 0x2U;
constexpr std::uint8_t kOpcodeClose = 0x8U;
constexpr std::uint8_t kOpcodePing = 0x9U;
constexpr std::uint8_t kOpcodePong = 0xAU;

using Deadline = std::chrono::steady_clock::time_point;

#if defined(_WIN32)
using NativeSocket = SOCKET;
constexpr NativeSocket kInvalidSocket = INVALID_SOCKET;
#else
using NativeSocket = int;
constexpr NativeSocket kInvalidSocket = -1;
#endif

struct PinContext final {
  std::array<std::uint8_t, kSha256Bytes> digest{};
};

struct WebSocketFrame final {
  bool final{false};
  std::uint8_t opcode{0U};
  std::vector<std::uint8_t> payload;
};

Status CancelledStatus() {
  return Status::Error(StatusCode::kFailedPrecondition,
                       "network operation cancelled");
}

#if !defined(_WIN32)
// OpenSSL's socket BIO can write during handshakes, reads, writes and shutdown.
// Blocking SIGPIPE only on the network-owner thread avoids a process-wide
// signal-policy change. A signal generated by this scope is consumed before
// restoring the caller's signal mask.
class ScopedSigpipeBlock final {
 public:
  ScopedSigpipeBlock() noexcept {
    if (sigemptyset(&sigpipe_set_) != 0 ||
        sigaddset(&sigpipe_set_, SIGPIPE) != 0) {
      return;
    }
    if (pthread_sigmask(SIG_BLOCK, &sigpipe_set_, &previous_mask_) != 0) {
      return;
    }
    mask_changed_ = true;
    const int previously_blocked = sigismember(&previous_mask_, SIGPIPE);
    if (previously_blocked < 0) {
      RestoreMask();
      return;
    }
    if (previously_blocked != 0) {
      ready_ = true;
      return;
    }
    owns_block_ = true;
    sigset_t pending{};
    if (sigpending(&pending) != 0) {
      RestoreMask();
      return;
    }
    const int previously_pending = sigismember(&pending, SIGPIPE);
    if (previously_pending < 0) {
      RestoreMask();
      return;
    }
    had_pending_sigpipe_ = previously_pending != 0;
    ready_ = true;
  }

  ~ScopedSigpipeBlock() {
    if (!mask_changed_) {
      return;
    }
    if (ready_ && owns_block_ && !had_pending_sigpipe_) {
      sigset_t pending{};
      if (sigpending(&pending) == 0 &&
          sigismember(&pending, SIGPIPE) == 1) {
        timespec no_wait{};
        while (sigtimedwait(&sigpipe_set_, nullptr, &no_wait) < 0 &&
               errno == EINTR) {
        }
      }
    }
    RestoreMask();
  }

  ScopedSigpipeBlock(const ScopedSigpipeBlock&) = delete;
  ScopedSigpipeBlock& operator=(const ScopedSigpipeBlock&) = delete;

  bool ready() const noexcept { return ready_; }

 private:
  void RestoreMask() noexcept {
    if (mask_changed_) {
      (void)pthread_sigmask(SIG_SETMASK, &previous_mask_, nullptr);
      mask_changed_ = false;
    }
  }

  sigset_t sigpipe_set_{};
  sigset_t previous_mask_{};
  bool mask_changed_{false};
  bool owns_block_{false};
  bool had_pending_sigpipe_{false};
  bool ready_{false};
};
#endif

Status OpenSslError(const char* const operation) {
  const unsigned long code = ERR_get_error();
  if (code == 0U) {
    return Status::Error(StatusCode::kInternal, operation);
  }
  std::array<char, 256> buffer{};
  ERR_error_string_n(code, buffer.data(), buffer.size());
  return Status::Error(StatusCode::kInternal,
                       std::string(operation) + ": " + buffer.data());
}

void CloseSocket(const NativeSocket socket) noexcept {
  if (socket == kInvalidSocket) {
    return;
  }
#if defined(_WIN32)
  closesocket(socket);
#else
  close(socket);
#endif
}

void ShutdownSocket(const NativeSocket socket) noexcept {
  if (socket == kInvalidSocket) {
    return;
  }
#if defined(_WIN32)
  (void)shutdown(socket, SD_BOTH);
#else
  (void)shutdown(socket, SHUT_RDWR);
#endif
}

Status InitializeSocketApi() {
#if defined(_WIN32)
  static const int result = []() {
    WSADATA data{};
    return WSAStartup(MAKEWORD(2, 2), &data);
  }();
  if (result != 0) {
    return Status::Error(StatusCode::kInternal,
                         "initialize Windows socket API failed");
  }
#endif
  return Status::Ok();
}

Status SetNonBlocking(const NativeSocket socket) {
#if defined(_WIN32)
  u_long enabled = 1U;
  if (ioctlsocket(socket, FIONBIO, &enabled) != 0) {
    return Status::Error(StatusCode::kInternal,
                         "set socket nonblocking mode failed");
  }
#else
  const int flags = fcntl(socket, F_GETFL, 0);
  if (flags < 0 || fcntl(socket, F_SETFL, flags | O_NONBLOCK) != 0) {
    return Status::Error(StatusCode::kInternal,
                         "set socket nonblocking mode failed");
  }
#endif
  return Status::Ok();
}

bool ConnectIsInProgress() {
#if defined(_WIN32)
  const int error = WSAGetLastError();
  return error == WSAEWOULDBLOCK || error == WSAEINPROGRESS ||
         error == WSAEINVAL;
#else
  return errno == EINPROGRESS;
#endif
}

Status WaitForSocket(const NativeSocket socket,
                     const bool wait_for_read,
                     const Deadline deadline,
                     const std::atomic<bool>& stop_requested) {
  for (;;) {
    if (stop_requested.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    const auto now = std::chrono::steady_clock::now();
    if (now >= deadline) {
      return Status::Error(StatusCode::kResourceExhausted,
                           "network operation timed out");
    }
    const auto remaining_us =
        std::chrono::duration_cast<std::chrono::microseconds>(deadline - now);
#if defined(_WIN32)
    timeval timeout{};
    timeout.tv_sec = static_cast<long>(remaining_us.count() / 1000000);
    timeout.tv_usec = static_cast<long>(remaining_us.count() % 1000000);

    fd_set read_set;
    fd_set write_set;
    FD_ZERO(&read_set);
    FD_ZERO(&write_set);
    if (wait_for_read) {
      FD_SET(socket, &read_set);
    } else {
      FD_SET(socket, &write_set);
    }
    const int result = select(0, wait_for_read ? &read_set : nullptr,
                              wait_for_read ? nullptr : &write_set, nullptr,
                              &timeout);
#else
    pollfd descriptor{};
    descriptor.fd = socket;
    descriptor.events = wait_for_read ? POLLIN : POLLOUT;
    const auto timeout_ms =
        static_cast<int>((remaining_us.count() + 999) / 1000);
    const int result = poll(&descriptor, 1U, timeout_ms);
#endif
    if (stop_requested.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    if (result > 0) {
#if !defined(_WIN32)
      if ((descriptor.revents & POLLNVAL) != 0) {
        return Status::Error(StatusCode::kInternal,
                             "network socket is invalid");
      }
#endif
      return Status::Ok();
    }
    if (result == 0) {
      return Status::Error(StatusCode::kResourceExhausted,
                           "network operation timed out");
    }
#if !defined(_WIN32)
    if (errno == EINTR) {
      continue;
    }
#endif
    return Status::Error(StatusCode::kInternal,
                         "wait for network socket failed");
  }
}

Status DecodeSha256Pin(const std::string& encoded,
                       std::array<std::uint8_t, kSha256Bytes>* const output) {
  if (output == nullptr || encoded.size() != 44U || encoded[43] != '=') {
    return Status::Error(StatusCode::kInvalidArgument,
                         "SPKI SHA-256 pin must be 44-byte base64");
  }
  std::array<unsigned char, 33> decoded{};
  const int decoded_size =
      EVP_DecodeBlock(decoded.data(),
                      reinterpret_cast<const unsigned char*>(encoded.data()),
                      static_cast<int>(encoded.size()));
  const std::size_t padding = encoded[42] == '=' ? 2U : 1U;
  if (decoded_size < 0 ||
      static_cast<std::size_t>(decoded_size) - padding != output->size()) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "SPKI SHA-256 pin is not valid base64");
  }
  std::copy_n(decoded.begin(), output->size(), output->begin());
  return Status::Ok();
}

int VerifyPinnedCertificate(X509_STORE_CTX* const store, void* const argument) {
  // A stable SPKI is the identity in pin mode, so wall-clock validity is
  // deliberately out of scope. TLS still proves possession of the matching
  // private key, while this callback enforces server purpose and the pin.
  const auto* const pin = static_cast<const PinContext*>(argument);
  X509* const certificate = X509_STORE_CTX_get0_cert(store);
  if (pin == nullptr || certificate == nullptr ||
      X509_check_purpose(certificate, X509_PURPOSE_SSL_SERVER, 0) <= 0) {
    X509_STORE_CTX_set_error(store, X509_V_ERR_CERT_REJECTED);
    return 0;
  }

  X509_PUBKEY* const public_key = X509_get_X509_PUBKEY(certificate);
  const int encoded_size = i2d_X509_PUBKEY(public_key, nullptr);
  if (encoded_size <= 0) {
    X509_STORE_CTX_set_error(store, X509_V_ERR_UNSPECIFIED);
    return 0;
  }
  std::array<unsigned char, 4096> encoded{};
  if (static_cast<std::size_t>(encoded_size) > encoded.size()) {
    X509_STORE_CTX_set_error(store, X509_V_ERR_UNSPECIFIED);
    return 0;
  }
  unsigned char* cursor = encoded.data();
  if (i2d_X509_PUBKEY(public_key, &cursor) != encoded_size) {
    X509_STORE_CTX_set_error(store, X509_V_ERR_UNSPECIFIED);
    return 0;
  }
  std::array<unsigned char, EVP_MAX_MD_SIZE> digest{};
  unsigned int digest_size = 0U;
  if (EVP_Digest(encoded.data(), static_cast<std::size_t>(encoded_size),
                 digest.data(), &digest_size, EVP_sha256(), nullptr) != 1 ||
      digest_size != pin->digest.size() ||
      CRYPTO_memcmp(digest.data(), pin->digest.data(), pin->digest.size()) !=
          0) {
    X509_STORE_CTX_set_error(store, X509_V_ERR_CERT_REJECTED);
    return 0;
  }
  X509_STORE_CTX_set_error(store, X509_V_OK);
  return 1;
}

std::string LowerAscii(std::string value) {
  std::transform(value.begin(), value.end(), value.begin(), [](const char ch) {
    return ch >= 'A' && ch <= 'Z' ? static_cast<char>(ch + ('a' - 'A')) : ch;
  });
  return value;
}

bool IsSafeServerName(const std::string& server_name) {
  if (server_name.empty() || server_name.size() > 253U) {
    return false;
  }
  return std::all_of(server_name.begin(), server_name.end(), [](const char ch) {
    const auto value = static_cast<unsigned char>(ch);
    return (value >= static_cast<unsigned char>('a') &&
            value <= static_cast<unsigned char>('z')) ||
           (value >= static_cast<unsigned char>('A') &&
            value <= static_cast<unsigned char>('Z')) ||
           (value >= static_cast<unsigned char>('0') &&
            value <= static_cast<unsigned char>('9')) ||
           ch == '-' || ch == '.' || ch == '_';
  });
}

std::string TrimAscii(const std::string& value) {
  const auto begin = value.find_first_not_of(" \t");
  if (begin == std::string::npos) {
    return {};
  }
  const auto end = value.find_last_not_of(" \t");
  return value.substr(begin, end - begin + 1U);
}

bool HeaderContainsToken(const std::string& value,
                         const std::string& expected_token) {
  std::size_t begin = 0U;
  while (begin <= value.size()) {
    const auto end = value.find(',', begin);
    const auto token = LowerAscii(TrimAscii(value.substr(
        begin, end == std::string::npos ? std::string::npos : end - begin)));
    if (token == expected_token) {
      return true;
    }
    if (end == std::string::npos) {
      break;
    }
    begin = end + 1U;
  }
  return false;
}

bool IsValidUtf8(const std::vector<std::uint8_t>& data) {
  std::size_t index = 0U;
  while (index < data.size()) {
    const std::uint8_t first = data[index++];
    if (first <= 0x7FU) {
      continue;
    }
    std::size_t continuation_count = 0U;
    std::uint32_t value = 0U;
    std::uint32_t minimum = 0U;
    if ((first & 0xE0U) == 0xC0U) {
      continuation_count = 1U;
      value = first & 0x1FU;
      minimum = 0x80U;
    } else if ((first & 0xF0U) == 0xE0U) {
      continuation_count = 2U;
      value = first & 0x0FU;
      minimum = 0x800U;
    } else if ((first & 0xF8U) == 0xF0U) {
      continuation_count = 3U;
      value = first & 0x07U;
      minimum = 0x10000U;
    } else {
      return false;
    }
    if (continuation_count > data.size() - index) {
      return false;
    }
    for (std::size_t count = 0U; count < continuation_count; ++count) {
      const std::uint8_t next = data[index++];
      if ((next & 0xC0U) != 0x80U) {
        return false;
      }
      value = (value << 6U) | (next & 0x3FU);
    }
    if (value < minimum || value > 0x10FFFFU ||
        (value >= 0xD800U && value <= 0xDFFFU)) {
      return false;
    }
  }
  return true;
}

std::string Base64Encode(const std::uint8_t* const data,
                         const std::size_t data_size) {
  std::string encoded(4U * ((data_size + 2U) / 3U), '\0');
  const int size = EVP_EncodeBlock(
      reinterpret_cast<unsigned char*>(encoded.data()), data,
      static_cast<int>(data_size));
  if (size <= 0) {
    return {};
  }
  encoded.resize(static_cast<std::size_t>(size));
  return encoded;
}

Status ExpectedWebSocketAccept(const std::string& key, std::string* output) {
  if (output == nullptr) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WebSocket accept output must not be null");
  }
  const std::string input = key + kWebSocketGuid;
  std::array<unsigned char, EVP_MAX_MD_SIZE> digest{};
  unsigned int digest_size = 0U;
  if (EVP_Digest(input.data(), input.size(), digest.data(), &digest_size,
                 EVP_sha1(), nullptr) != 1 ||
      digest_size != 20U) {
    return OpenSslError("compute WebSocket handshake digest failed");
  }
  *output = Base64Encode(digest.data(), digest_size);
  if (output->empty()) {
    return Status::Error(StatusCode::kInternal,
                         "encode WebSocket handshake digest failed");
  }
  return Status::Ok();
}

}  // namespace

class WssClient::Impl final {
 public:
  explicit Impl(WssClientConfig config) : config_(std::move(config)) {}
  ~Impl() { Reset(); }

  Status Connect();
  Status SendControl(const std::string& control_json);
  Status SendPcm(const protocol::AudioPacketHeader& header,
                 const std::uint8_t* payload,
                 std::size_t payload_size_bytes);
  Status SendKeepAlivePong();
  Status Receive(WssInboundMessage* output);
  void RequestStop() noexcept;
  void Close() noexcept;
  bool connected() const noexcept { return connected_; }

 private:
  Status ConnectTcp(const Deadline deadline);
  Status ConfigureTls();
  Status ConnectTls(const Deadline deadline);
  Status UpgradeWebSocket(const Deadline deadline);
  Status WriteTls(const std::uint8_t* data,
                  std::size_t data_size,
                  const Deadline deadline);
  Status ReadTls(std::uint8_t* data,
                 std::size_t data_size,
                 const Deadline deadline);
  Status SendFrame(std::uint8_t opcode,
                   const std::uint8_t* payload,
                   std::size_t payload_size,
                   const Deadline deadline);
  Status ReadFrame(WebSocketFrame* output, const Deadline deadline);
  Status ReadDataMessage(std::uint8_t* opcode,
                         std::vector<std::uint8_t>* payload);
  void Reset() noexcept;

  WssClientConfig config_;
  PinContext pin_{};
  NativeSocket socket_{kInvalidSocket};
  SSL_CTX* tls_context_{nullptr};
  SSL* tls_{nullptr};
  bool connected_{false};
  std::atomic<bool> stop_requested_{false};
  std::mutex socket_lifetime_mutex_;
};

Status WssClient::Impl::Connect() {
  if (connected_ || socket_ != kInvalidSocket || tls_context_ != nullptr ||
      tls_ != nullptr) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WSS client is already connected");
  }
  stop_requested_.store(false, std::memory_order_release);
  const auto config_status = ValidateWssClientConfig(config_);
  if (!config_status.ok()) {
    return config_status;
  }
  const auto socket_status = InitializeSocketApi();
  if (!socket_status.ok()) {
    return socket_status;
  }
  if (!config_.spki_sha256_base64.empty()) {
    const auto pin_status =
        DecodeSha256Pin(config_.spki_sha256_base64, &pin_.digest);
    if (!pin_status.ok()) {
      return pin_status;
    }
  }
  const auto deadline = std::chrono::steady_clock::now() +
                        std::chrono::milliseconds(config_.connect_timeout_ms);
  auto status = ConnectTcp(deadline);
  if (status.ok()) {
    status = ConfigureTls();
  }
  if (status.ok()) {
    status = ConnectTls(deadline);
  }
  if (status.ok()) {
    status = UpgradeWebSocket(deadline);
  }
  if (status.ok() &&
      stop_requested_.load(std::memory_order_acquire)) {
    status = CancelledStatus();
  }
  if (!status.ok()) {
    Reset();
    return status;
  }
  connected_ = true;
  return Status::Ok();
}

Status WssClient::Impl::ConnectTcp(const Deadline deadline) {
  if (stop_requested_.load(std::memory_order_acquire)) {
    return CancelledStatus();
  }
  sockaddr_storage address{};
  socklen_t address_size = 0;
  int family = AF_UNSPEC;
  auto* const ipv4 = reinterpret_cast<sockaddr_in*>(&address);
  if (inet_pton(AF_INET, config_.server_ip.c_str(), &ipv4->sin_addr) == 1) {
    family = AF_INET;
    ipv4->sin_family = AF_INET;
    ipv4->sin_port = htons(config_.server_port);
    address_size = sizeof(*ipv4);
  } else {
    auto* const ipv6 = reinterpret_cast<sockaddr_in6*>(&address);
    if (inet_pton(AF_INET6, config_.server_ip.c_str(), &ipv6->sin6_addr) != 1) {
      return Status::Error(StatusCode::kInvalidArgument,
                           "server_ip must be a numeric IPv4 or IPv6 address");
    }
    family = AF_INET6;
    ipv6->sin6_family = AF_INET6;
    ipv6->sin6_port = htons(config_.server_port);
    address_size = sizeof(*ipv6);
  }

  const NativeSocket created_socket = socket(family, SOCK_STREAM, IPPROTO_TCP);
  if (created_socket == kInvalidSocket) {
    return Status::Error(StatusCode::kInternal,
                         "create TCP socket failed");
  }
  {
    std::lock_guard<std::mutex> lock(socket_lifetime_mutex_);
    if (stop_requested_.load(std::memory_order_acquire)) {
      CloseSocket(created_socket);
      return CancelledStatus();
    }
    socket_ = created_socket;
  }
  const auto mode_status = SetNonBlocking(socket_);
  if (!mode_status.ok()) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    return mode_status;
  }
  const int result = connect(socket_, reinterpret_cast<const sockaddr*>(&address),
                             address_size);
  if (result == 0) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    return Status::Ok();
  }
  if (!ConnectIsInProgress()) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    return Status::Error(StatusCode::kInternal,
                         "connect TCP socket failed");
  }
  const auto wait_status =
      WaitForSocket(socket_, false, deadline, stop_requested_);
  if (!wait_status.ok()) {
    return wait_status;
  }
  if (stop_requested_.load(std::memory_order_acquire)) {
    return CancelledStatus();
  }
  int socket_error = 0;
#if defined(_WIN32)
  int error_size = sizeof(socket_error);
#else
  socklen_t error_size = sizeof(socket_error);
#endif
  if (getsockopt(socket_, SOL_SOCKET, SO_ERROR,
                 reinterpret_cast<char*>(&socket_error), &error_size) != 0 ||
      socket_error != 0) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    return Status::Error(StatusCode::kInternal,
                         "complete TCP connection failed");
  }
  if (stop_requested_.load(std::memory_order_acquire)) {
    return CancelledStatus();
  }
  return Status::Ok();
}

Status WssClient::Impl::ConfigureTls() {
  tls_context_ = SSL_CTX_new(TLS_client_method());
  if (tls_context_ == nullptr) {
    return OpenSslError("create TLS client context failed");
  }
  if (SSL_CTX_set_min_proto_version(tls_context_, TLS1_2_VERSION) != 1) {
    return OpenSslError("require TLS 1.2 failed");
  }
  SSL_CTX_set_options(tls_context_, SSL_OP_NO_COMPRESSION);
  SSL_CTX_set_verify(tls_context_, SSL_VERIFY_PEER, nullptr);
  if (!config_.spki_sha256_base64.empty()) {
    SSL_CTX_set_cert_verify_callback(tls_context_, VerifyPinnedCertificate,
                                     &pin_);
  } else if (SSL_CTX_load_verify_locations(
                 tls_context_, config_.ca_certificate_path.c_str(), nullptr) !=
             1) {
    return OpenSslError("load server CA certificate failed");
  } else {
    X509_VERIFY_PARAM_set_flags(SSL_CTX_get0_param(tls_context_),
                                X509_V_FLAG_PARTIAL_CHAIN);
  }

  tls_ = SSL_new(tls_context_);
  if (tls_ == nullptr) {
    return OpenSslError("create TLS connection failed");
  }
  if (SSL_set_fd(tls_, static_cast<int>(socket_)) != 1) {
    return OpenSslError("attach TLS connection to socket failed");
  }
  if (!config_.server_name.empty() &&
      SSL_set_tlsext_host_name(tls_, config_.server_name.c_str()) != 1) {
    return OpenSslError("set TLS server name failed");
  }
  if (config_.spki_sha256_base64.empty() &&
      SSL_set1_host(tls_, config_.server_name.c_str()) != 1) {
    return OpenSslError("set TLS certificate hostname failed");
  }
  constexpr std::array<unsigned char, 9> kHttp11Alpn{
      {8U, 'h', 't', 't', 'p', '/', '1', '.', '1'}};
  if (SSL_set_alpn_protos(tls_, kHttp11Alpn.data(), kHttp11Alpn.size()) != 0) {
    return OpenSslError("set TLS ALPN failed");
  }
  return Status::Ok();
}

Status WssClient::Impl::ConnectTls(const Deadline deadline) {
#if !defined(_WIN32)
  ScopedSigpipeBlock sigpipe_block;
  if (!sigpipe_block.ready()) {
    return Status::Error(StatusCode::kInternal,
                         "block SIGPIPE for TLS handshake failed");
  }
#endif
  for (;;) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    ERR_clear_error();
    const int result = SSL_connect(tls_);
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    if (result == 1) {
      // Certificate-authenticated TLS completes only after the peer proves it
      // owns the private key corresponding to the accepted certificate SPKI.
      break;
    }
    const int error = SSL_get_error(tls_, result);
    if (error != SSL_ERROR_WANT_READ && error != SSL_ERROR_WANT_WRITE) {
      return OpenSslError("TLS handshake failed");
    }
    const auto wait_status =
        WaitForSocket(socket_, error == SSL_ERROR_WANT_READ, deadline,
                      stop_requested_);
    if (!wait_status.ok()) {
      return wait_status;
    }
  }
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
  X509* const peer = SSL_get1_peer_certificate(tls_);
#else
  X509* const peer = SSL_get_peer_certificate(tls_);
#endif
  if (peer == nullptr) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "TLS server did not present a certificate");
  }
  X509_free(peer);
  if (SSL_get_verify_result(tls_) != X509_V_OK) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "TLS server certificate verification failed");
  }
  return Status::Ok();
}

Status WssClient::Impl::UpgradeWebSocket(const Deadline deadline) {
  std::array<std::uint8_t, 16> nonce{};
  if (RAND_bytes(nonce.data(), nonce.size()) != 1) {
    return OpenSslError("generate WebSocket handshake nonce failed");
  }
  const std::string key = Base64Encode(nonce.data(), nonce.size());
  if (key.empty()) {
    return Status::Error(StatusCode::kInternal,
                         "encode WebSocket handshake nonce failed");
  }
  const bool is_ipv6 = config_.server_ip.find(':') != std::string::npos;
  const std::string authority_host =
      !config_.server_name.empty()
          ? config_.server_name
          : (is_ipv6 ? "[" + config_.server_ip + "]" : config_.server_ip);
  const std::string host =
      authority_host + ":" + std::to_string(config_.server_port);
  const std::string request =
      std::string("GET ") + kWebSocketPath + " HTTP/1.1\r\nHost: " + host +
      "\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n" +
      "Sec-WebSocket-Key: " + key +
      "\r\nSec-WebSocket-Version: 13\r\n\r\n";
  auto status = WriteTls(reinterpret_cast<const std::uint8_t*>(request.data()),
                         request.size(), deadline);
  if (!status.ok()) {
    return status;
  }

  std::string response;
  response.reserve(512U);
  while (response.size() < kMaximumHandshakeBytes &&
         (response.size() < 4U ||
          response.compare(response.size() - 4U, 4U, "\r\n\r\n") != 0)) {
    std::uint8_t byte = 0U;
    status = ReadTls(&byte, 1U, deadline);
    if (!status.ok()) {
      return status;
    }
    response.push_back(static_cast<char>(byte));
  }
  if (response.size() >= kMaximumHandshakeBytes ||
      response.compare(response.size() - 4U, 4U, "\r\n\r\n") != 0) {
    return Status::Error(StatusCode::kResourceExhausted,
                         "WebSocket handshake response is too large");
  }

  std::istringstream stream(response);
  std::string line;
  if (!std::getline(stream, line)) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "server rejected WebSocket upgrade");
  }
  if (!line.empty() && line.back() == '\r') {
    line.pop_back();
  }
  std::istringstream status_line(line);
  std::string http_version;
  unsigned int http_status = 0U;
  if (!(status_line >> http_version >> http_status) ||
      (http_version != "HTTP/1.1" && http_version != "HTTP/1.0") ||
      http_status != 101U) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "server rejected WebSocket upgrade");
  }
  std::string upgrade;
  std::string connection;
  std::string accept;
  while (std::getline(stream, line) && line != "\r") {
    if (!line.empty() && line.back() == '\r') {
      line.pop_back();
    }
    const auto separator = line.find(':');
    if (separator == std::string::npos) {
      return Status::Error(StatusCode::kInvalidArgument,
                           "malformed WebSocket handshake header");
    }
    const auto name = LowerAscii(TrimAscii(line.substr(0U, separator)));
    const auto value = TrimAscii(line.substr(separator + 1U));
    if (name == "upgrade") {
      upgrade = value;
    } else if (name == "connection") {
      connection = value;
    } else if (name == "sec-websocket-accept") {
      accept = value;
    }
  }
  std::string expected_accept;
  status = ExpectedWebSocketAccept(key, &expected_accept);
  if (!status.ok()) {
    return status;
  }
  if (LowerAscii(upgrade) != "websocket" ||
      !HeaderContainsToken(connection, "upgrade") ||
      accept != expected_accept) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WebSocket upgrade response verification failed");
  }
  return Status::Ok();
}

Status WssClient::Impl::WriteTls(const std::uint8_t* data,
                                 const std::size_t data_size,
                                 const Deadline deadline) {
#if !defined(_WIN32)
  ScopedSigpipeBlock sigpipe_block;
  if (!sigpipe_block.ready()) {
    return Status::Error(StatusCode::kInternal,
                         "block SIGPIPE for TLS write failed");
  }
#endif
  std::size_t offset = 0U;
  while (offset < data_size) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    const auto remaining = std::min<std::size_t>(
        data_size - offset, static_cast<std::size_t>(std::numeric_limits<int>::max()));
    ERR_clear_error();
    const int result =
        SSL_write(tls_, data + offset, static_cast<int>(remaining));
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    if (result > 0) {
      offset += static_cast<std::size_t>(result);
      continue;
    }
    const int error = SSL_get_error(tls_, result);
    if (error != SSL_ERROR_WANT_READ && error != SSL_ERROR_WANT_WRITE) {
      return OpenSslError("write TLS stream failed");
    }
    const auto wait_status =
        WaitForSocket(socket_, error == SSL_ERROR_WANT_READ, deadline,
                      stop_requested_);
    if (!wait_status.ok()) {
      return wait_status;
    }
  }
  return Status::Ok();
}

Status WssClient::Impl::ReadTls(std::uint8_t* data,
                                const std::size_t data_size,
                                const Deadline deadline) {
#if !defined(_WIN32)
  ScopedSigpipeBlock sigpipe_block;
  if (!sigpipe_block.ready()) {
    return Status::Error(StatusCode::kInternal,
                         "block SIGPIPE for TLS read failed");
  }
#endif
  std::size_t offset = 0U;
  while (offset < data_size) {
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    const auto remaining = std::min<std::size_t>(
        data_size - offset, static_cast<std::size_t>(std::numeric_limits<int>::max()));
    ERR_clear_error();
    const int result = SSL_read(tls_, data + offset, static_cast<int>(remaining));
    if (stop_requested_.load(std::memory_order_acquire)) {
      return CancelledStatus();
    }
    if (result > 0) {
      offset += static_cast<std::size_t>(result);
      continue;
    }
    const int error = SSL_get_error(tls_, result);
    if (error == SSL_ERROR_ZERO_RETURN) {
      return Status::Error(StatusCode::kFailedPrecondition,
                           "TLS peer closed the connection");
    }
    if (error != SSL_ERROR_WANT_READ && error != SSL_ERROR_WANT_WRITE) {
      return OpenSslError("read TLS stream failed");
    }
    const auto wait_status =
        WaitForSocket(socket_, error == SSL_ERROR_WANT_READ, deadline,
                      stop_requested_);
    if (!wait_status.ok()) {
      return wait_status;
    }
  }
  return Status::Ok();
}

Status WssClient::Impl::SendFrame(const std::uint8_t opcode,
                                  const std::uint8_t* const payload,
                                  const std::size_t payload_size,
                                  const Deadline deadline) {
  if (payload_size > 0U && payload == nullptr) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WebSocket payload must not be null");
  }
  if (payload_size > kMaximumWireMessageBytes) {
    return Status::Error(StatusCode::kResourceExhausted,
                         "WebSocket payload exceeds protocol bound");
  }
  if (opcode >= kOpcodeClose && payload_size > 125U) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WebSocket control payload exceeds 125 bytes");
  }

  std::vector<std::uint8_t> frame;
  const std::size_t length_bytes =
      payload_size < 126U ? 0U : (payload_size <= 0xFFFFU ? 2U : 8U);
  frame.resize(2U + length_bytes + 4U + payload_size);
  frame[0] = static_cast<std::uint8_t>(0x80U | opcode);
  std::size_t cursor = 2U;
  if (length_bytes == 0U) {
    frame[1] = static_cast<std::uint8_t>(0x80U | payload_size);
  } else if (length_bytes == 2U) {
    frame[1] = 0x80U | 126U;
    frame[cursor++] = static_cast<std::uint8_t>((payload_size >> 8U) & 0xFFU);
    frame[cursor++] = static_cast<std::uint8_t>(payload_size & 0xFFU);
  } else {
    frame[1] = 0x80U | 127U;
    const auto wire_size = static_cast<std::uint64_t>(payload_size);
    for (int shift = 56; shift >= 0; shift -= 8) {
      frame[cursor++] =
          static_cast<std::uint8_t>((wire_size >> shift) & 0xFFU);
    }
  }
  std::array<std::uint8_t, 4> mask{};
  if (RAND_bytes(mask.data(), mask.size()) != 1) {
    return OpenSslError("generate WebSocket frame mask failed");
  }
  std::copy(mask.begin(), mask.end(), frame.begin() + cursor);
  cursor += mask.size();
  for (std::size_t index = 0U; index < payload_size; ++index) {
    frame[cursor + index] = payload[index] ^ mask[index % mask.size()];
  }
  return WriteTls(frame.data(), frame.size(), deadline);
}

Status WssClient::Impl::ReadFrame(WebSocketFrame* const output,
                                  const Deadline deadline) {
  if (output == nullptr) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WebSocket frame output must not be null");
  }
  std::array<std::uint8_t, 2> header{};
  auto status = ReadTls(header.data(), header.size(), deadline);
  if (!status.ok()) {
    return status;
  }
  if ((header[0] & 0x70U) != 0U) {
    return Status::Error(StatusCode::kNotSupported,
                         "WebSocket extensions are not negotiated");
  }
  if ((header[1] & 0x80U) != 0U) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "server WebSocket frames must not be masked");
  }
  const bool final = (header[0] & 0x80U) != 0U;
  const std::uint8_t opcode = header[0] & 0x0FU;
  std::uint64_t payload_size = header[1] & 0x7FU;
  if (payload_size == 126U) {
    std::array<std::uint8_t, 2> length{};
    status = ReadTls(length.data(), length.size(), deadline);
    if (!status.ok()) {
      return status;
    }
    payload_size = (static_cast<std::uint64_t>(length[0]) << 8U) | length[1];
  } else if (payload_size == 127U) {
    std::array<std::uint8_t, 8> length{};
    status = ReadTls(length.data(), length.size(), deadline);
    if (!status.ok()) {
      return status;
    }
    if ((length[0] & 0x80U) != 0U) {
      return Status::Error(StatusCode::kInvalidArgument,
                           "WebSocket payload length has the reserved high bit");
    }
    payload_size = 0U;
    for (const std::uint8_t byte : length) {
      payload_size = (payload_size << 8U) | byte;
    }
  }
  const bool is_control = opcode >= kOpcodeClose;
  if ((is_control && (!final || payload_size > 125U)) ||
      payload_size > kMaximumWireMessageBytes) {
    return Status::Error(StatusCode::kResourceExhausted,
                         "WebSocket frame violates protocol bounds");
  }
  WebSocketFrame frame{};
  frame.final = final;
  frame.opcode = opcode;
  frame.payload.resize(static_cast<std::size_t>(payload_size));
  status = ReadTls(frame.payload.data(), frame.payload.size(), deadline);
  if (!status.ok()) {
    return status;
  }
  *output = std::move(frame);
  return Status::Ok();
}

Status WssClient::Impl::ReadDataMessage(
    std::uint8_t* const opcode,
    std::vector<std::uint8_t>* const payload) {
  if (opcode == nullptr || payload == nullptr) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WebSocket message output must not be null");
  }
  bool fragmented = false;
  payload->clear();
  auto idle_deadline =
      std::chrono::steady_clock::now() +
      std::chrono::milliseconds(config_.receive_idle_timeout_ms);
  for (;;) {
    WebSocketFrame frame{};
    auto status = ReadFrame(&frame, idle_deadline);
    if (!status.ok()) {
      return status;
    }
    idle_deadline = std::chrono::steady_clock::now() +
                    std::chrono::milliseconds(
                        config_.receive_idle_timeout_ms);
    if (frame.opcode == kOpcodePing) {
      const auto write_deadline =
          std::chrono::steady_clock::now() +
          std::chrono::milliseconds(config_.write_timeout_ms);
      status = SendFrame(kOpcodePong, frame.payload.data(),
                         frame.payload.size(), write_deadline);
      if (!status.ok()) {
        return status;
      }
      idle_deadline = std::chrono::steady_clock::now() +
                      std::chrono::milliseconds(
                          config_.receive_idle_timeout_ms);
      continue;
    }
    if (frame.opcode == kOpcodePong) {
      continue;
    }
    if (frame.opcode == kOpcodeClose) {
      return Status::Error(StatusCode::kFailedPrecondition,
                           "WebSocket peer closed the connection");
    }
    if (frame.opcode == kOpcodeContinuation) {
      if (!fragmented) {
        return Status::Error(StatusCode::kInvalidArgument,
                             "unexpected WebSocket continuation frame");
      }
    } else if (frame.opcode == kOpcodeText || frame.opcode == kOpcodeBinary) {
      if (fragmented) {
        return Status::Error(StatusCode::kInvalidArgument,
                             "new WebSocket message interrupted fragments");
      }
      *opcode = frame.opcode;
      fragmented = !frame.final;
    } else {
      return Status::Error(StatusCode::kNotSupported,
                           "unsupported WebSocket frame opcode");
    }
    if (frame.payload.size() > kMaximumWireMessageBytes - payload->size()) {
      return Status::Error(StatusCode::kResourceExhausted,
                           "fragmented WebSocket message exceeds protocol bound");
    }
    payload->insert(payload->end(), frame.payload.begin(), frame.payload.end());
    if (frame.final) {
      return Status::Ok();
    }
  }
}

Status WssClient::Impl::SendControl(const std::string& control_json) {
  if (!connected_) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WSS client is not connected");
  }
  if (control_json.empty() ||
      control_json.size() > protocol::kMaximumControlFrameBytes) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "control frame size is outside protocol bounds");
  }
  const std::vector<std::uint8_t> bytes(control_json.begin(),
                                        control_json.end());
  if (!IsValidUtf8(bytes)) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "control frame is not valid UTF-8");
  }
  const auto deadline = std::chrono::steady_clock::now() +
                        std::chrono::milliseconds(config_.write_timeout_ms);
  return SendFrame(kOpcodeText,
                   reinterpret_cast<const std::uint8_t*>(control_json.data()),
                   control_json.size(), deadline);
}

Status WssClient::Impl::SendPcm(
    const protocol::AudioPacketHeader& header,
    const std::uint8_t* const payload,
    const std::size_t payload_size_bytes) {
  if (!connected_) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WSS client is not connected");
  }
  if (header.kind != protocol::AudioPacketKind::kUplink ||
      header.sample_rate_hz != 16000U ||
      payload_size_bytes != header.payload_length_bytes ||
      (payload_size_bytes > 0U && payload == nullptr)) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "uplink PCM must be matching 16 kHz protocol audio");
  }
  std::array<std::uint8_t, protocol::kAudioPacketHeaderSize> encoded_header{};
  auto status = protocol::EncodeAudioPacketHeader(header, &encoded_header);
  if (!status.ok()) {
    return status;
  }
  std::vector<std::uint8_t> frame(encoded_header.begin(), encoded_header.end());
  frame.insert(frame.end(), payload, payload + payload_size_bytes);
  const auto deadline = std::chrono::steady_clock::now() +
                        std::chrono::milliseconds(config_.write_timeout_ms);
  return SendFrame(kOpcodeBinary, frame.data(), frame.size(), deadline);
}

Status WssClient::Impl::SendKeepAlivePong() {
  if (!connected_) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WSS client is not connected");
  }
  const auto deadline = std::chrono::steady_clock::now() +
                        std::chrono::milliseconds(config_.write_timeout_ms);
  return SendFrame(kOpcodePong, nullptr, 0U, deadline);
}

Status WssClient::Impl::Receive(WssInboundMessage* const output) {
  if (output == nullptr) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WSS receive output must not be null");
  }
  if (!connected_) {
    return Status::Error(StatusCode::kFailedPrecondition,
                         "WSS client is not connected");
  }
  std::uint8_t opcode = 0U;
  std::vector<std::uint8_t> payload;
  auto status = ReadDataMessage(&opcode, &payload);
  if (!status.ok()) {
    return status;
  }

  WssInboundMessage message{};
  if (opcode == kOpcodeText) {
    if (payload.empty() ||
        payload.size() > protocol::kMaximumControlFrameBytes ||
        !IsValidUtf8(payload)) {
      return Status::Error(StatusCode::kInvalidArgument,
                           "received control frame is invalid UTF-8 or size");
    }
    message.type = WssInboundMessageType::kControl;
    message.control_json.assign(payload.begin(), payload.end());
  } else {
    protocol::AudioPacketHeader header{};
    status = protocol::DecodeAudioPacketHeader(payload.data(), payload.size(),
                                               &header);
    if (!status.ok()) {
      return status;
    }
    if (header.kind != protocol::AudioPacketKind::kDownlink ||
        header.sample_rate_hz != 24000U) {
      return Status::Error(StatusCode::kFailedPrecondition,
                           "downlink PCM must be protocol v1 24 kHz mono");
    }
    message.type = WssInboundMessageType::kPcm24k;
    message.pcm_header = header;
    message.pcm_payload.assign(
        payload.begin() +
            static_cast<std::ptrdiff_t>(protocol::kAudioPacketHeaderSize),
        payload.end());
  }
  *output = std::move(message);
  return Status::Ok();
}

void WssClient::Impl::RequestStop() noexcept {
  stop_requested_.store(true, std::memory_order_release);
  std::lock_guard<std::mutex> lock(socket_lifetime_mutex_);
  ShutdownSocket(socket_);
}

void WssClient::Impl::Close() noexcept {
  if (connected_ && tls_ != nullptr &&
      !stop_requested_.load(std::memory_order_acquire)) {
    const auto deadline = std::chrono::steady_clock::now() +
                          std::chrono::milliseconds(250U);
    const std::array<std::uint8_t, 2> normal_close{{0x03U, 0xE8U}};
    (void)SendFrame(kOpcodeClose, normal_close.data(), normal_close.size(),
                    deadline);
#if defined(_WIN32)
    (void)SSL_shutdown(tls_);
#else
    ScopedSigpipeBlock sigpipe_block;
    if (sigpipe_block.ready()) {
      (void)SSL_shutdown(tls_);
    }
#endif
  }
  Reset();
}

void WssClient::Impl::Reset() noexcept {
  connected_ = false;
  if (tls_ != nullptr) {
    SSL_free(tls_);
    tls_ = nullptr;
  }
  if (tls_context_ != nullptr) {
    SSL_CTX_free(tls_context_);
    tls_context_ = nullptr;
  }
  NativeSocket socket_to_close = kInvalidSocket;
  {
    std::lock_guard<std::mutex> lock(socket_lifetime_mutex_);
    socket_to_close = socket_;
    socket_ = kInvalidSocket;
  }
  CloseSocket(socket_to_close);
}

WssClient::WssClient(WssClientConfig config)
    : impl_(std::make_unique<Impl>(std::move(config))) {}

WssClient::~WssClient() = default;

Status WssClient::Connect() { return impl_->Connect(); }

Status WssClient::SendControl(const std::string& control_json) {
  return impl_->SendControl(control_json);
}

Status WssClient::SendPcm(const protocol::AudioPacketHeader& header,
                          const std::uint8_t* const payload,
                          const std::size_t payload_size_bytes) {
  return impl_->SendPcm(header, payload, payload_size_bytes);
}

Status WssClient::SendKeepAlivePong() {
  return impl_->SendKeepAlivePong();
}

Status WssClient::Receive(WssInboundMessage* const output) {
  return impl_->Receive(output);
}

void WssClient::RequestStop() noexcept { impl_->RequestStop(); }

void WssClient::Close() noexcept { impl_->Close(); }

bool WssClient::connected() const noexcept { return impl_->connected(); }

Status ValidateWssClientConfig(const WssClientConfig& config) {
  if (config.server_ip.empty()) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WSS server IP must not be empty");
  }
  if (config.server_port == 0U) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WSS server port must be non-zero");
  }
  const bool has_ca = !config.ca_certificate_path.empty();
  const bool has_pin = !config.spki_sha256_base64.empty();
  if (has_ca == has_pin) {
    return Status::Error(
        StatusCode::kInvalidArgument,
        "configure exactly one of CA certificate or SPKI SHA-256 pin");
  }
  if (has_ca && config.server_name.empty()) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "CA verification requires a TLS server name");
  }
  if (!config.server_name.empty() && !IsSafeServerName(config.server_name)) {
    return Status::Error(
        StatusCode::kInvalidArgument,
        "TLS server name must use a bounded safe ASCII host character set");
  }
  if (has_pin) {
    std::array<std::uint8_t, kSha256Bytes> pin{};
    const auto pin_status = DecodeSha256Pin(config.spki_sha256_base64, &pin);
    if (!pin_status.ok()) {
      return pin_status;
    }
  }
  if (config.connect_timeout_ms == 0U ||
      config.connect_timeout_ms > 60000U || config.write_timeout_ms == 0U ||
      config.write_timeout_ms > 60000U) {
    return Status::Error(StatusCode::kInvalidArgument,
                         "WSS connect/write timeouts must be between 1 and 60000 ms");
  }
  if (config.receive_idle_timeout_ms == 0U ||
      config.receive_idle_timeout_ms > 120000U) {
    return Status::Error(
        StatusCode::kInvalidArgument,
        "WSS receive idle timeout must be between 1 and 120000 ms");
  }
  return Status::Ok();
}

}  // namespace boompi::network
