set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(NOT DEFINED BOOMPI_RV1106_TOOLCHAIN_ROOT OR BOOMPI_RV1106_TOOLCHAIN_ROOT STREQUAL "")
  if(DEFINED ENV{BOOMPI_RV1106_TOOLCHAIN_ROOT} AND NOT "$ENV{BOOMPI_RV1106_TOOLCHAIN_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{BOOMPI_RV1106_TOOLCHAIN_ROOT}" BOOMPI_RV1106_TOOLCHAIN_ROOT)
  else()
    message(FATAL_ERROR
      "Set BOOMPI_RV1106_TOOLCHAIN_ROOT as an environment variable or CMake cache path")
  endif()
endif()
set(BOOMPI_RV1106_TOOLCHAIN_ROOT "${BOOMPI_RV1106_TOOLCHAIN_ROOT}" CACHE PATH
  "Root directory of the RV1106 cross toolchain")

if(NOT DEFINED BOOMPI_RV1106_TOOLCHAIN_PREFIX OR BOOMPI_RV1106_TOOLCHAIN_PREFIX STREQUAL "")
  if(DEFINED ENV{BOOMPI_RV1106_TOOLCHAIN_PREFIX} AND NOT "$ENV{BOOMPI_RV1106_TOOLCHAIN_PREFIX}" STREQUAL "")
    set(BOOMPI_RV1106_TOOLCHAIN_PREFIX "$ENV{BOOMPI_RV1106_TOOLCHAIN_PREFIX}")
  else()
    set(BOOMPI_RV1106_TOOLCHAIN_PREFIX "arm-rockchip830-linux-uclibcgnueabihf")
  endif()
endif()
set(BOOMPI_RV1106_TOOLCHAIN_PREFIX "${BOOMPI_RV1106_TOOLCHAIN_PREFIX}" CACHE STRING
  "Executable prefix of the RV1106 cross compiler")

find_program(CMAKE_C_COMPILER
  NAMES "${BOOMPI_RV1106_TOOLCHAIN_PREFIX}-gcc"
  PATHS
    "${BOOMPI_RV1106_TOOLCHAIN_ROOT}/bin"
    "${BOOMPI_RV1106_TOOLCHAIN_ROOT}"
  NO_DEFAULT_PATH
  REQUIRED)
find_program(CMAKE_CXX_COMPILER
  NAMES "${BOOMPI_RV1106_TOOLCHAIN_PREFIX}-g++"
  PATHS
    "${BOOMPI_RV1106_TOOLCHAIN_ROOT}/bin"
    "${BOOMPI_RV1106_TOOLCHAIN_ROOT}"
  NO_DEFAULT_PATH
  REQUIRED)

if(NOT DEFINED BOOMPI_RV1106_SYSROOT OR BOOMPI_RV1106_SYSROOT STREQUAL "")
  if(DEFINED ENV{BOOMPI_RV1106_SYSROOT} AND NOT "$ENV{BOOMPI_RV1106_SYSROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{BOOMPI_RV1106_SYSROOT}" BOOMPI_RV1106_SYSROOT)
  endif()
endif()

if(DEFINED BOOMPI_RV1106_SYSROOT AND NOT BOOMPI_RV1106_SYSROOT STREQUAL "")
  set(BOOMPI_RV1106_SYSROOT "${BOOMPI_RV1106_SYSROOT}" CACHE PATH
    "RV1106 target sysroot")
  set(CMAKE_SYSROOT "${BOOMPI_RV1106_SYSROOT}")
  list(APPEND CMAKE_FIND_ROOT_PATH "${BOOMPI_RV1106_SYSROOT}")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
